# Generated by Django 5.0.1 on 2024-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0005_alter_author_born_date_alter_author_born_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
